# Generated by Django 4.1.5 on 2025-09-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distination',
            name='days',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='distination',
            name='location',
            field=models.CharField(default='india', max_length=100),
        ),
        migrations.AddField(
            model_name='distination',
            name='rate',
            field=models.FloatField(default=7, max_length=10),
        ),
    ]
